Fix: Remove inheritance error due to missing function in NeptuneGremlinProxy (#1308)
* Fix: Remove inheritance error in NeptuneGremlinProxy

```
  File "/app/metadata_service/proxy/__init__.py", line 47, in get_proxy_client
    client_kwargs=client_kwargs)
TypeError: Can't instantiate abstract class NeptuneGremlinProxy with abstract methods get_popular_resources
```

Signed-off-by: Rajat Jaiswal <rajat.jaiswal@hotstar.com>

* change pass to NotImplemented

Signed-off-by: Rajat Jaiswal <rajat.jaiswal@hotstar.com>

* fix indent

Signed-off-by: Rajat Jaiswal <rajat.jaiswal@hotstar.com>
Signed-off-by: Amom <amommendes@hotmail.com>